# Generated by Django 3.2 on 2021-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Categories'),
        ),
    ]
