# Generated by Django 3.2 on 2021-12-13 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/benaldo66/image/upload/v1639388818/nabbljv3vqkucvcafw0p.jpg', max_length=255, verbose_name='image'),
        ),
    ]
